/gate/source/addSource twogamma
/gate/source/twogamma/setActivity 1000 becquerel
/gate/source/twogamma/setType backtoback
/gate/source/twogamma/gps/particle gamma
/gate/source/twogamma/gps/energytype Mono
/gate/source/twogamma/gps/monoenergy 0.511 MeV
/gate/source/twogamma/gps/type Volume
/gate/source/twogamma/gps/shape Sphere
/gate/source/twogamma/gps/radius 0.001 mm
/gate/source/twogamma/gps/centre 0. 120. -125. mm
/gate/source/twogamma/gps/angtype iso
/gate/source/twogamma/gps/mintheta 0. deg
/gate/source/twogamma/gps/maxtheta 0. deg
/gate/source/twogamma/gps/minphi 90. deg
/gate/source/twogamma/gps/maxphi 90. deg

/gate/source/list
