/gate/source/addSource SingleGamma
/gate/source/SingleGamma/setActivity 20000. becquerel
/gate/source/SingleGamma/gps/particle gamma
/gate/source/SingleGamma/gps/energytype Mono
/gate/source/SingleGamma/gps/monoenergy 0.511 MeV
/gate/source/SingleGamma/gps/type Volume
/gate/source/SingleGamma/gps/shape Sphere
/gate/source/SingleGamma/gps/radius 0.001 mm
/gate/source/SingleGamma/gps/angtype iso
/gate/source/SingleGamma/gps/centre 0 0 0 mm

/gate/source/list


#/gate/source/F18/gps/shape Sphere
#/gate/source/F18/gps/radius 0.001 mm
#/gate/source/F18/gps/centre 0. 0. 0. mm

#/gate/source/SingleGamma/gps/shape Cylinder
#/gate/source/SingleGamma/gps/radius 24 mm
#/gate/source/SingleGamma/gps/halfz 59 mm